export const iconMap = {
  Attack: "sword",
  Defence: "shield",
  Strength: "zap",
  Hitpoints: "heart",
  Ranged: "bow-arrow",
  Prayer: "sparkles",
  Magic: "wand-sparkles",
  Cooking: "chef-hat",
  Woodcutting: "axe",
  Fletching: "navigation",
  Fishing: "fish",
  Firemaking: "flame",
  Crafting: "scissors",
  Smithing: "hammer",
  Mining: "pickaxe",
  Herblore: "flask-conical",
  Agility: "activity",
  Thieving: "hand",
  Slayer: "skull",
  Farming: "sprout",
  Runecraft: "circle-slash-2",
  Hunter: "footprints",
  Construction: "home",
};
